-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('echo_pb')


ECHO = protobuf.Descriptor();
local ECHO_DATA_FIELD = protobuf.FieldDescriptor();

ECHO_DATA_FIELD.name = "data"
ECHO_DATA_FIELD.full_name = ".pb.Echo.data"
ECHO_DATA_FIELD.number = 1
ECHO_DATA_FIELD.index = 0
ECHO_DATA_FIELD.label = 2
ECHO_DATA_FIELD.has_default_value = false
ECHO_DATA_FIELD.default_value = ""
ECHO_DATA_FIELD.type = 9
ECHO_DATA_FIELD.cpp_type = 9

ECHO.name = "Echo"
ECHO.full_name = ".pb.Echo"
ECHO.nested_types = {}
ECHO.enum_types = {}
ECHO.fields = {ECHO_DATA_FIELD}
ECHO.is_extendable = false
ECHO.extensions = {}

Echo = protobuf.Message(ECHO)

