-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('game_pb')


MOVEREQUEST = protobuf.Descriptor();
local MOVEREQUEST_SRC_X_FIELD = protobuf.FieldDescriptor();
local MOVEREQUEST_SRC_Y_FIELD = protobuf.FieldDescriptor();
MOVERESPONSE = protobuf.Descriptor();
local MOVERESPONSE_CODE_FIELD = protobuf.FieldDescriptor();
NOTIFYMOVE = protobuf.Descriptor();
local NOTIFYMOVE_PLAYER_USER_ID_FIELD = protobuf.FieldDescriptor();
local NOTIFYMOVE_SRC_X_FIELD = protobuf.FieldDescriptor();
local NOTIFYMOVE_SRC_Y_FIELD = protobuf.FieldDescriptor();

MOVEREQUEST_SRC_X_FIELD.name = "src_x"
MOVEREQUEST_SRC_X_FIELD.full_name = ".pb.MoveRequest.src_x"
MOVEREQUEST_SRC_X_FIELD.number = 1
MOVEREQUEST_SRC_X_FIELD.index = 0
MOVEREQUEST_SRC_X_FIELD.label = 2
MOVEREQUEST_SRC_X_FIELD.has_default_value = false
MOVEREQUEST_SRC_X_FIELD.default_value = 0
MOVEREQUEST_SRC_X_FIELD.type = 5
MOVEREQUEST_SRC_X_FIELD.cpp_type = 1

MOVEREQUEST_SRC_Y_FIELD.name = "src_y"
MOVEREQUEST_SRC_Y_FIELD.full_name = ".pb.MoveRequest.src_y"
MOVEREQUEST_SRC_Y_FIELD.number = 2
MOVEREQUEST_SRC_Y_FIELD.index = 1
MOVEREQUEST_SRC_Y_FIELD.label = 2
MOVEREQUEST_SRC_Y_FIELD.has_default_value = false
MOVEREQUEST_SRC_Y_FIELD.default_value = 0
MOVEREQUEST_SRC_Y_FIELD.type = 5
MOVEREQUEST_SRC_Y_FIELD.cpp_type = 1

MOVEREQUEST.name = "MoveRequest"
MOVEREQUEST.full_name = ".pb.MoveRequest"
MOVEREQUEST.nested_types = {}
MOVEREQUEST.enum_types = {}
MOVEREQUEST.fields = {MOVEREQUEST_SRC_X_FIELD, MOVEREQUEST_SRC_Y_FIELD}
MOVEREQUEST.is_extendable = false
MOVEREQUEST.extensions = {}
MOVERESPONSE_CODE_FIELD.name = "code"
MOVERESPONSE_CODE_FIELD.full_name = ".pb.MoveResponse.code"
MOVERESPONSE_CODE_FIELD.number = 1
MOVERESPONSE_CODE_FIELD.index = 0
MOVERESPONSE_CODE_FIELD.label = 2
MOVERESPONSE_CODE_FIELD.has_default_value = false
MOVERESPONSE_CODE_FIELD.default_value = 0
MOVERESPONSE_CODE_FIELD.type = 5
MOVERESPONSE_CODE_FIELD.cpp_type = 1

MOVERESPONSE.name = "MoveResponse"
MOVERESPONSE.full_name = ".pb.MoveResponse"
MOVERESPONSE.nested_types = {}
MOVERESPONSE.enum_types = {}
MOVERESPONSE.fields = {MOVERESPONSE_CODE_FIELD}
MOVERESPONSE.is_extendable = false
MOVERESPONSE.extensions = {}
NOTIFYMOVE_PLAYER_USER_ID_FIELD.name = "player_user_id"
NOTIFYMOVE_PLAYER_USER_ID_FIELD.full_name = ".pb.NotifyMove.player_user_id"
NOTIFYMOVE_PLAYER_USER_ID_FIELD.number = 1
NOTIFYMOVE_PLAYER_USER_ID_FIELD.index = 0
NOTIFYMOVE_PLAYER_USER_ID_FIELD.label = 2
NOTIFYMOVE_PLAYER_USER_ID_FIELD.has_default_value = false
NOTIFYMOVE_PLAYER_USER_ID_FIELD.default_value = 0
NOTIFYMOVE_PLAYER_USER_ID_FIELD.type = 5
NOTIFYMOVE_PLAYER_USER_ID_FIELD.cpp_type = 1

NOTIFYMOVE_SRC_X_FIELD.name = "src_x"
NOTIFYMOVE_SRC_X_FIELD.full_name = ".pb.NotifyMove.src_x"
NOTIFYMOVE_SRC_X_FIELD.number = 2
NOTIFYMOVE_SRC_X_FIELD.index = 1
NOTIFYMOVE_SRC_X_FIELD.label = 2
NOTIFYMOVE_SRC_X_FIELD.has_default_value = false
NOTIFYMOVE_SRC_X_FIELD.default_value = 0
NOTIFYMOVE_SRC_X_FIELD.type = 5
NOTIFYMOVE_SRC_X_FIELD.cpp_type = 1

NOTIFYMOVE_SRC_Y_FIELD.name = "src_y"
NOTIFYMOVE_SRC_Y_FIELD.full_name = ".pb.NotifyMove.src_y"
NOTIFYMOVE_SRC_Y_FIELD.number = 3
NOTIFYMOVE_SRC_Y_FIELD.index = 2
NOTIFYMOVE_SRC_Y_FIELD.label = 2
NOTIFYMOVE_SRC_Y_FIELD.has_default_value = false
NOTIFYMOVE_SRC_Y_FIELD.default_value = 0
NOTIFYMOVE_SRC_Y_FIELD.type = 5
NOTIFYMOVE_SRC_Y_FIELD.cpp_type = 1

NOTIFYMOVE.name = "NotifyMove"
NOTIFYMOVE.full_name = ".pb.NotifyMove"
NOTIFYMOVE.nested_types = {}
NOTIFYMOVE.enum_types = {}
NOTIFYMOVE.fields = {NOTIFYMOVE_PLAYER_USER_ID_FIELD, NOTIFYMOVE_SRC_X_FIELD, NOTIFYMOVE_SRC_Y_FIELD}
NOTIFYMOVE.is_extendable = false
NOTIFYMOVE.extensions = {}

MoveRequest = protobuf.Message(MOVEREQUEST)
MoveResponse = protobuf.Message(MOVERESPONSE)
NotifyMove = protobuf.Message(NOTIFYMOVE)

