-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('login_sign_pb')


LOGINREWARD = protobuf.Descriptor();
local LOGINREWARD_INDEX_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_TYPE_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_CONTENT_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_COUNT_FIELD = protobuf.FieldDescriptor();

LOGINREWARD_INDEX_FIELD.name = "index"
LOGINREWARD_INDEX_FIELD.full_name = ".pb.LoginReward.index"
LOGINREWARD_INDEX_FIELD.number = 1
LOGINREWARD_INDEX_FIELD.index = 0
LOGINREWARD_INDEX_FIELD.label = 2
LOGINREWARD_INDEX_FIELD.has_default_value = false
LOGINREWARD_INDEX_FIELD.default_value = 0
LOGINREWARD_INDEX_FIELD.type = 5
LOGINREWARD_INDEX_FIELD.cpp_type = 1

LOGINREWARD_TYPE_FIELD.name = "type"
LOGINREWARD_TYPE_FIELD.full_name = ".pb.LoginReward.type"
LOGINREWARD_TYPE_FIELD.number = 2
LOGINREWARD_TYPE_FIELD.index = 1
LOGINREWARD_TYPE_FIELD.label = 2
LOGINREWARD_TYPE_FIELD.has_default_value = false
LOGINREWARD_TYPE_FIELD.default_value = ""
LOGINREWARD_TYPE_FIELD.type = 9
LOGINREWARD_TYPE_FIELD.cpp_type = 9

LOGINREWARD_CONTENT_FIELD.name = "content"
LOGINREWARD_CONTENT_FIELD.full_name = ".pb.LoginReward.content"
LOGINREWARD_CONTENT_FIELD.number = 3
LOGINREWARD_CONTENT_FIELD.index = 2
LOGINREWARD_CONTENT_FIELD.label = 2
LOGINREWARD_CONTENT_FIELD.has_default_value = false
LOGINREWARD_CONTENT_FIELD.default_value = ""
LOGINREWARD_CONTENT_FIELD.type = 9
LOGINREWARD_CONTENT_FIELD.cpp_type = 9

LOGINREWARD_COUNT_FIELD.name = "count"
LOGINREWARD_COUNT_FIELD.full_name = ".pb.LoginReward.count"
LOGINREWARD_COUNT_FIELD.number = 4
LOGINREWARD_COUNT_FIELD.index = 3
LOGINREWARD_COUNT_FIELD.label = 2
LOGINREWARD_COUNT_FIELD.has_default_value = false
LOGINREWARD_COUNT_FIELD.default_value = 0
LOGINREWARD_COUNT_FIELD.type = 5
LOGINREWARD_COUNT_FIELD.cpp_type = 1

LOGINREWARD.name = "LoginReward"
LOGINREWARD.full_name = ".pb.LoginReward"
LOGINREWARD.nested_types = {}
LOGINREWARD.enum_types = {}
LOGINREWARD.fields = {LOGINREWARD_INDEX_FIELD, LOGINREWARD_TYPE_FIELD, LOGINREWARD_CONTENT_FIELD, LOGINREWARD_COUNT_FIELD}
LOGINREWARD.is_extendable = false
LOGINREWARD.extensions = {}

LoginReward = protobuf.Message(LOGINREWARD)

