-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('server_pb')


READYTIMEOUT = protobuf.Descriptor();
local READYTIMEOUT_SEAT_ID_FIELD = protobuf.FieldDescriptor();

READYTIMEOUT_SEAT_ID_FIELD.name = "seat_id"
READYTIMEOUT_SEAT_ID_FIELD.full_name = ".pb.ReadyTimeout.seat_id"
READYTIMEOUT_SEAT_ID_FIELD.number = 1
READYTIMEOUT_SEAT_ID_FIELD.index = 0
READYTIMEOUT_SEAT_ID_FIELD.label = 2
READYTIMEOUT_SEAT_ID_FIELD.has_default_value = false
READYTIMEOUT_SEAT_ID_FIELD.default_value = 0
READYTIMEOUT_SEAT_ID_FIELD.type = 5
READYTIMEOUT_SEAT_ID_FIELD.cpp_type = 1

READYTIMEOUT.name = "ReadyTimeout"
READYTIMEOUT.full_name = ".pb.ReadyTimeout"
READYTIMEOUT.nested_types = {}
READYTIMEOUT.enum_types = {}
READYTIMEOUT.fields = {READYTIMEOUT_SEAT_ID_FIELD}
READYTIMEOUT.is_extendable = false
READYTIMEOUT.extensions = {}

ReadyTimeout = protobuf.Message(READYTIMEOUT)

